### ISSUE TITLE
Error with Gcloud CLI

### ISSUE THREAD

**Issue by rdoume** [operatorai/kettle#33]
Hi,

I found your repo within the mlops.community and I wanted to try it out, with no luck so far.
I installed it using linuxbrew (Ubuntu 16.04), and go is not my strong suit, so it's not so easy to debug myself.
When starting with operator init, and choosing GCP as a a platform, I get the message 

`please install the gcloud cli`

However, the CLI is installed, as I use it on a daily basis. 
Could you help me get around this?

**Comment by nlathia** [comment]
👋 Hey @rdoume, thanks for letting me know!

Under the hood, this tool is running ([here](https://github.com/operatorai/operator/blob/main/clouds/gcloud.go#L25-L27)) `command -v gcloud` to check whether the gcloud CLI is installed. Here is the [Ubuntu manpage](http://manpages.ubuntu.com/manpages/trusty/man1/command.1posix.html) on that command.

If you run that command in a terminal, what is the output?

**Comment by nlathia** [comment]
I've set up a docker container to run `ubuntu:16.04` (and installed `gcloud` on it) to diagnose this a bit further:

```
root@de50958063d5:~/src# lsb_release -d
Description:	Ubuntu 16.04.7 LTS

root@de50958063d5:~/src# command -v gcloud
/usr/bin/gcloud

root@de50958063d5:~/src# which command
root@de50958063d5:~/src# 
```

The problem here is that Go fails with:
```
panic: exec: "command": executable file not found in $PATH`
```

Which seems to be the same problem that is discussed [here on stackoverflow](https://stackoverflow.com/questions/34229486/how-to-execute-a-shell-built-in-command); i.e., that `command` is a shell built-in, rather than a command, and so it cannot be found in the `$PATH`. 

It looks like I can resolve this by using `type` instead of `command` -- I'll get that fixed in the repo ASAP 😄

**Comment by nlathia** [comment]
I've merged https://github.com/operatorai/operator/pull/34 which I believe should fix this. I'll do some more thorough testing on Ubuntu soon - but, in the meantime, if you run into any other issues please let me know 🙏

**Comment by rdoume** [comment]
Hey Neal, I'm trying this out and keep you posted!

**Comment by nlathia** [comment]
I've run into the error again on a fresh Ubuntu 16.04 container 😞 

Am doing some more investigation

**Comment by nlathia** [comment]
Okay _this time_ I think I've fixed it https://github.com/operatorai/operator/pull/35

**Comment by nlathia** [comment]
Am renaming the project to `kettle` and moving the templates out permanently. Will close this for now, let me know if you spot any other issues!
